### ISSUE TITLE
Pre-check connected ctez and/or oracle accounts have the right interfaces

### ISSUE THREAD

**Issue by purcell** [tezos-checker/checker#107]
When we seal the contract we should perhaps check that we can ping the ctez and/or oracle contracts, to check they are compatible. It’s a bit silly in some ways, but if other people are deploying checker then some sanity checks might be helpful.

**Comment by utdemir** [comment]
Turns out this was implemented as part of #120: https://github.com/tezos-checker/checker/pull/120/files#diff-feb4c256779da0e2b88751b43636cd95fa4c62a130f1974b278f91caf6b1b4a4R68-R70
