### ISSUE TITLE
Delegation auction for the uniswap funds

### ISSUE THREAD

**Issue by murbard** [tezos-checker/checker#11]
Gather around folks, it's the delegation auction brain dump.

The general idea is the following: having funds delegated to you is valuable, and bakers are willing to pay for it. They usually do so by sharing baking rewards  after the fact with their delegators, but there's nothing stopping them from paying upfront.

Checker's uniswap contract holds tez and, as such, it has a valuable delegation option.

### A few rejected options

**Voting:**

One approach would be to let the liquidity providers vote on the delegate but, unfortunately, one with 50% could vote themselves as the baker and keep everything.

**Seggregated accounts for liquidty providers:**

Another approach would be to let each liquidity provider control the delegate of the tez that they provide in a seggregated contract (not unlike how burrows have their own delegator). But what happens when someone sells kit and needs to receive tez? They can't receive tez proportionally from each seggregated account (it wouldn't be O(1)). So instead we do the following: first, we keep track of how many tez each seggregated account ought to have, based on liquidity shares. Then, when someone needs to receive tez, they get a ticket that they can present to _any_ of the seggregated accounts to get their tez, so long as this account doesn't have more tez than they ought to have based on their liquidity share. Of course, as soon as this happens, this account will have less than they ought to have and, mathematically, some accounts will have more. To fix this, we let anyone perform rebalancing operations that take tez from an account that has more than they ought to have and transfer it to an account that has less. The idea is that small deviations from fairness are tolerated which means that we don't need O(n) transactions every time.

This is an interesting primitive that lets users simulate pooled tez while keeping baking rights, but it's heavy and there's no telling how much rebalancing will be needed in practice.

**Protocol modification**

One option would be to support this kind of pooling at the protocol level directly, by letting smart-contracts select an arbitrary number of bakers (or maybe, say 100) with some apportionment expressed as fractions. But this takes some time to implement due to how "rolls" work, and it still requires some care on the smart-contract side.

### Selected option

**Auction for delegator**

The current approach I would suggest is to simply auction the delegation right. 

A naive version of this approach would be as follow: let bakers bid for the right to bake the contract, and the highest bidder is automatically set as the delegate.

That version doesn't work because liquidity providers could time the snapshot of the delegation state and remove their liquidity right at this point to point to their own delegator, and then put it back. We don't want to force liquidity providers to stay in the contract either.

What we do instead is ensure that the bid payed by the baker does not accrue to the pool until one cycle has passed. For the purpose of *adding liquidity*, we act as if the bid accrues immediately, for the purpose of *removing liquidity* we act as if the bid doesn't accrue for an entire cycle.

This essentially mean that liquidity providers might lose up to a cycle's worth of baking when they get in and out. That's about 0.04% though, so nothing to be too concerned over.

So how does this work?

An ascending bid auction takes place during a cycle and ends on the last block of the cycle. We know where we are in a cycle by using `LEVEL mod 4096`. The baker’s bid accrues to the pool at the conclusion of the following auction. So if a baker bids during cycle n, he will become the baker on the first block of cycle n+1 and until the last block of cycle n+1. The bid will accrue to the pool on the first block of cycle n+2, for the purposes of withdrawing liquidity.

**Comment by gkaracha** [comment]
Since the checker no longer has a delegation auction I think we can close this issue.
