### ISSUE TITLE
Provide FA2/TZIP-16 views to support UX

### ISSUE THREAD

**Issue by purcell** [tezos-checker/checker#121]
In order to expose various metrics (e.g. whether a burrow is currently overburrowed, approx. minting capacity etc.) various calculations are necessary using data stored on-chain. These calculations should be performed using the same code that is used in Checker itself, rather than trying to reimplement logic in javascript. 

The best way to achieve this is probably to provide FA2 views, ie. pack additional michelson functions into the deployed contract's storage, such that clients can invoke it.

We are awaiting info about specific required metrics, and will discuss/plan further here in due course.

(See also #96.)

**Comment by gkaracha** [comment]
I think that by now we have added a sufficient number of views to consider this issue resolved. `checker.mli` on the current [HEAD](https://github.com/tezos-checker/checker/commit/f0f5ed5c2d40a09d0da87ac83eb0565402ba0735) seems to contain the following views: 
```ocaml
(* CFMM-related views *)
val view_buy_kit_min_kit_expected : (ctok * checker) -> kit
val view_sell_kit_min_ctok_expected : (kit * checker) -> ctok
val view_add_liquidity_max_kit_deposited : (ctok * checker) -> kit
val view_add_liquidity_min_lqt_minted : (ctok * checker) -> lqt
val view_remove_liquidity_min_ctok_withdrawn : (lqt * checker) -> ctok
val view_remove_liquidity_min_kit_withdrawn : (lqt * checker) -> kit

(* Liquidation-auction-related views *)
val view_current_liquidation_auction_details: (unit * checker) -> view_current_liquidation_auction_details_result

(* Burrow-related views *)
val view_burrow_max_mintable_kit : (burrow_id * checker) -> kit
val view_is_burrow_overburrowed : (burrow_id * checker) -> bool
val view_is_burrow_liquidatable : (burrow_id * checker) -> bool

(* FA2 views *)
val view_get_balance : ((Ligo.address * fa2_token_id) * checker) -> Ligo.nat
val view_total_supply : (fa2_token_id * checker) -> Ligo.nat
val view_all_tokens : (unit * checker) -> fa2_token_id list
val view_is_operator : ((Ligo.address * (Ligo.address * fa2_token_id)) * checker) -> bool
```
Let's close this one now; we can open individual issues when specific views are requested.
