### ISSUE TITLE
Make a command line client for deploying checker

### ISSUE THREAD

**Issue by utdemir** [tezos-checker/checker#123]
Compiling and deploying checker is not trivial; since it requires a set of scripts to 

1. Transpilate ocaml to ligo
2. Separately compile the main contract and the lazy entrypoints
3. Deploy the main contract, then the lazy entrypoints
4. Seal the contract passing the necessary addresses for contracts it depends on

Steps 1 and 2 is required only when developing checker, so we can just share the resulting artifacts for deployment.

This issue is to create a script to do the step 3 and 4.

Currently we have a shell script to do the deployment; but I think using `pytezos` here will have some benefits on testing front, because then we can also write some end to end tests on Python, which is more plesant to write tests in than a shell script.

**Comment by dorranh** [comment]
@utdemir, do you think that #127 + #130 cover this issue? Wanted to double check before closing.

**Comment by utdemir** [comment]
Yes, definitely. Thanks!
