### ISSUE TITLE
Need backup maintainer for readthedocs integration

### ISSUE THREAD

**Issue by purcell** [tezos-checker/checker#125]
Please can one or more people sign up on readthedocs.io, probably with their github account, and let me know their username there so that I can add them as a maintainer. If I am unavailable and changes are needed, someone else should have access.

(Note: link for an existing maintainer to add further maintainers is [here](https://readthedocs.org/dashboard/checker/users/).)

**Comment by purcell** [comment]
Me and @0xd34df00d so far, would be good to have one more.

**Comment by utdemir** [comment]
I registered as `utdemir`, happy to be a maintainer.

**Comment by purcell** [comment]
Thanks, will consider this done now.
