### ISSUE TITLE
Missing unit/property tests for FA2-related entrypoints

### ISSUE THREAD

**Issue by gkaracha** [tezos-checker/checker#152]
While going through `tests/testChecker.ml` I noticed that we have no unit tests for the three FA2-related entrypoints:
```
Checker.strict_entrypoint_transfer
Checker.strict_entrypoint_balance_of
Checker.entrypoint_update_operators
```
We only have one test per function, checking that they fail when `Tezos.amount > 0tez`. We should add a few unit tests for edge cases, and perhaps some property-based tests for more general properties.

**Comment by purcell** [comment]
Done
