### ISSUE TITLE
Straw-man mutation testing tool

### ISSUE THREAD

**Issue by gkaracha** [tezos-checker/checker#168]
We recently discussed the possibility of using mutation testing for increasing test coverage, so I am opening this issue to discuss our options. 

As far as I can tell, there is no mutation testing tool for OCaml at the moment and rolling out our own from scratch is perhaps too big a detour given how narrow our use-case is. However, there might be low-hanging fruit we can leverage to get to an MVP that is immediately useful for our purposes, even if it's not general-purpose.

Common/useful mutations
---
[Earlier work on Haskell](https://www.uh.edu/serg/publications/fp-mutation.pdf) (and other resources I've found online) have already identified several transformations that are suitable for functional languages. The following (or a subset of them) might be a good starting point for us:

* Replace an integer constant `N` by one of `{0, 1, -1, N+1, N-1}`.
* Replace an arithmetic / relational / logical operator by another in the same class.
* Negate a conditional.
* Reorder pattern matching equations.
* Remove pattern matching equations.
* Replace a random list by the empty list `[]`.
* Replace a `(head :: tail)` list by `tail`.
* Replace a `(head :: tail)` list by `[head]`.
* Replace `(list1 @ list2)` by `list1`.
* Replace `(list1 @ list2)` by `list2`.
* Replace `(list1 @ list2)` by `(list2 @ list1)`.

Possible approach
---
Since most of the above transformations are syntactic, we could get a poor-man's mutation testing tool for checker by using an off-the-shelf OCaml parser to allow us to generate patches (for example [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml) might be sufficient), which we can then separately apply to the source code before executing the testsuite. Separating the patch-generation phase from the test execution is nice, since it will probably allow us to maximally parallelize the execution of tests.

**Comment by murbard** [comment]
An even poorer's man mutation testing framework is sed. Literally just turning some <= into < will reveal interesting things

**Comment by purcell** [comment]
Yup, `sed` is on our radar too. Main thing is having a structured way of working through possible mutations one at a time, and re-running the tests for each. The property tests take a few minutes to run, and we'd like to keep using them under mutation, so if there are lots of permutations then efficiency is a concern.

**Comment by murbard** [comment]
1. Single mutations work best, the number of mutations should be essentially linear in the length of the codebase
2. Push come to shove that framework can be a combination of git branch and sed in a shell script :)
2. In some sense, not running the property tests makes your mutation testing stronger, it forces you to have a unit test specifically designed to showcase the rationale behind that + sign or that - sign, or that >= condition.

**Comment by purcell** [comment]
Yeah, we talked about all of this yesterday, and agree re. the property tests. We're doing some hacky early work to explore the state of play. Already found a few cases where tests don't fail under mutation, at least for the non-property tests.

**Comment by murbard** [comment]
Exciting!

**Comment by gkaracha** [comment]
Our `mutate.py` script (based on `git`, indeed) has been working sufficiently well, so I think we can safely close this one now.
