### ISSUE TITLE
Generated integer mutations in mutate.py are not always actual mutations

### ISSUE THREAD

**Issue by dorranh** [tezos-checker/checker#186]
As noted by @gkaracha, sometimes mutate.py will generate "mutations" which are actually just an identity transformation (e.g. mutating `Ligo.int_from_literal "0"` to `Ligo.int_from_literal "0"`. This occurs because the current implementation selects possible mutations from a list, not accounting for the fact that input integer might be equal to one of the mutations in the list. We should update mutate.py to filter out these cases.

https://github.com/tezos-checker/checker/blob/d05caf304c816dcb6c4a3cc3662adca4383b7823/scripts/mutate.py#L136

**Comment by gkaracha** [comment]
Probably just filtering out the equal ones from the list of options should be enough to fix this:

```diff
diff --git a/scripts/mutate.py b/scripts/mutate.py
index 9f780ad..8cd4b0d 100755
--- a/scripts/mutate.py
+++ b/scripts/mutate.py
@@ -131,9 +131,13 @@ def mutate_integer_literal(value_src: str) -> str:
         if value == 0:
             mutated_value = 1
         else:
-            mutated_value = random.choice([0, 1, value + 1, value - 1])
+            options_list = [0, 1, value + 1, value - 1]
+            real_options = list(filter(lambda x: (x != value), options_list))
+            mutated_value = random.choice(real_options)
     else:
-        mutated_value = random.choice([-1, 0, 1, value + 1, value - 1])
+        options_list = [-1, 0, 1, value + 1, value - 1]
+        real_options = list(filter(lambda x: (x != value), options_list))
+        mutated_value = random.choice(real_options)
 
     return f"{mutated_value:_}{suffix}"
```
