### ISSUE TITLE
Profiling in end to end tests

### ISSUE THREAD

**Issue by dorranh** [tezos-checker/checker#194]
Now that we have an end to end test for liquidation auctions, it would be interesting to add some basic execution time (edit: gas cost) profiling to the various liquidation auction methods to attempt to detect degenerating efficiency (e.g. non-constant complexity for cancelling slices). As a part of this we can also shuffle the order of slices to ensure we are touching slices interior to the queue as suggested here https://github.com/tezos-checker/checker/pull/193#discussion_r668550626.

**Comment by murbard** [comment]
By time, we should mean gas consumption really.
