### ISSUE TITLE
Offline views failing on granadanet?

### ISSUE THREAD

**Issue by gkaracha** [tezos-checker/checker#247]
@zgorizzo69 pointed out that `metadataViews.buy_kit_min_kit_expected()` and other offline views seem to be failing on the recent [granadanet deployment of checker](https://better-call.dev/granadanet/KT1FfHEMmoDy8oDuckRinLdDBt4qS6JCQhoe/operations).

**Comment by dorranh** [comment]
Hmm, when I run this view I always get back `0` and not an error. Perhaps no-one has added liquidity to the CFMM yet?

**Comment by dorranh** [comment]
@gkaracha, I think we might be able to close this issue now. Would you agree?

**Comment by gkaracha** [comment]
Yeah @dorranh, feel free to do so, given that you don't get the error Benjamin reported. @zgorizzo69 shout if you're still getting that error.

**Comment by zgorizzo69** [comment]
Ok for me
