### ISSUE TITLE
Generalize checker to be able to replicate tokens on chain

### ISSUE THREAD

**Issue by gkaracha** [tezos-checker/checker#263]
Taken from #171 (Part 3):

> We can distinguish two big classes of contracts: those that attempt to replicate an index provided by an oracle (index-based), and those that attempt to replicate an existing token on the chain (token-based)
> 1. For index-based we use the index, the ctez / tez cfmm price, and the ctez / kit cfmm price, with the ctez / kit cfmm being subsidized by the checker contract.
> 2. For token-based, the setup is typically a bit different. Suppose we want to replicate USDS using tzBTC as collateral. In that case, we would want to derive prices from 3 cfmms, USDS / cUSDS, tzBTC / ctez and USDS / ctez, with the USDs / cUSDS pair being subsidized by the checker contract.

Though the technical details of how to allow checker at build/deployment time switch from index-based (current design) to token-based mode are currently unclear, I'm opening this issue so that we can keep all relevant discussion in one place.

Though perhaps generalization in this axis is orthogonal to #213, I'd recommend we address this after #213 is completed.

**Comment by gkaracha** [comment]
Some of my notes from today's meeting, capturing my understanding of the three different setups we'll have once all generalizations are completed:
1. index-based, collateral = tez
2. index-based, collateral = fa2
3. token-based, collateral = fa2

Index-based, collateral = wtez (TEZ)
---
```
(pegged to CHF)
collateral = TEZ
cfmm = { kit & ctez }
issued = kit

1. TEZ/CHF  (from the index)
2. ctez/kit (from Checker's CFMM)

3. TEZ/ctez (from ctez's CFMM)

(collateralization) Minting/liquidation needs TEZ/CHF : p1
(price adjustment)  Drift adjustment needs kit/CHF    : p1 / ( p2 * p3 )
```

Index-based, collateral = tok (FA2)
---
```
(pegged to CHF)
collateral = tok
cfmm = { kit & tok }
issued = kit

1. tok/CHF (from the index)
2. tok/kit (from Checker's CFMM)

(collateralization) Minting/liquidation needs tok/CHF : p1
(price adjustment)  Drift adjustment needs kit/CHF    : p1 / p2
```

Token-based, collateral = tok (FA2)
---
```
(replicating tzCHF)
collateral = tok
cfmm = { kit & tzCHF }
issued = kit

1. tok/tzCHF (from onchain CFMM, as an oracle)
2. tzCHF/kit (from Checker's CFMM)

(collateralization) Minting/liquidation needs tok/tzCHF : p1
(price adjustment)  Drift adjustment needs kit/tzCHF    : 1 / p2
```

**Comment by gkaracha** [comment]
Some more details on this.

**Type discrepancy**: The index is usually tez-denominated, so it's common to give it as a `nat`. This is also the representation we currently use in `parameters.ml`. However, CFMMs are more likely to represent prices a ratio `pair nat nat` (fraction of the two token pools). Most likely we need to preemptively change the internal representation of the index into a ratio. In index-based checkers we can always create the fraction on the fly (by dividing with the appropriate scaling factor) and in token-based checker's we can simply convert the pair given into a ratio. This way the rest of the codebase can remain agnostic to what we are tracking.

**Entrypoint name**: Currently there is no standard for the name of the entrypoint providing the needed price. Let's assume for now that the price-offering entrypoint will be named `cfmm_oracle`, though this might change. Probably a good idea to have this be configurable.

**Comment by gkaracha** [comment]
wip list of TODOs to address this:

- [ ] Change `parameters.ml` such that `index : ratio` and `protected_index : ratio`.
- [ ] Resort to one more jinja template for the price calculation variation.
- [ ] Implement a mock cfmm, offering only the desired entrypoint `cfmm_oracle : (nat * nat) contract`

**Comment by dorranh** [comment]
This might be a silly question, but I wonder if there is a standard regarding the units of the ratio exposed by the cfmm. I feel like there is room for someone to accidentally plug in the inverse of the ratio we expect in Checker. It would be nice if there was a standard for this (e.g. some contract metadata describing the respective token symbols of the numerator and denominator).

**Comment by gkaracha** [comment]
Ah, that's a great point! I know of no such standard, and we already had the same issue with the marginal price tez/ctez we get from the ctez contract. I don't know if there's any such precedent; @murbard will surely have more to say on this.
