### ISSUE TITLE
Update protocol to Hangzhou

### ISSUE THREAD

**Issue by dorranh** [tezos-checker/checker#297]
Once Hangzhou is released on mainnet (I think this should happen within the next week or so), we should upgrade the protocol in our project (used for sandbox, tests, etc.). This will likely involve:

- [x] Updating the version of flextesa we are building in our Earthfile (`+flextesa` target). It looks like flextesa has simplified their build process, so we can also likely simplify our fairly manual build steps at the same time, relying on their `Makefile` instead.
- [x] Updating the protocol in `checker_client.checker.start_local_sandbox`
- [ ] Updating the default protocol in `scripts/compile-ligo.rb`. Alternatively, we can also remove this from the script since we are not measuring the contract size on CI anymore (instead measuring the serialized entrypoints themselves).

**Comment by dorranh** [comment]
Closed in #315 (not that I think that we might want to just remove the `tezos-client` calls in `compile-ligo` since we no longer really use that functionality.

**Comment by gkaracha** [comment]
> not that I think that we might want to just remove the `tezos-client` calls in `compile-ligo` since we no longer really use that functionality.

Ah, yes, this has come up before. I'd be OK with either (a) removing the calls to `tezos-client`, or (b) restoring the `tezos-client` dependency so that we actually get to see again the size the contracts we generate.
