### ISSUE TITLE
`earthly +test` currently fails due to deprecation alerts

### ISSUE THREAD

**Issue by emturner** [tezos-checker/checker#322]
when running the tests, a few errors appear:

```
+test-ocaml *failed* | File "tests/testAvlModel.ml", line 5, characters 5-22:
+test-ocaml *failed* | 5 | open Core_kernel.Deque
+test-ocaml *failed* |          ^^^^^^^^^^^^^^^^^
+test-ocaml *failed* | Error (alert deprecated): module Core_kernel
+test-ocaml *failed* | [since 2021-05] Use [Core] -- [Core_kernel] was renamed as [Core]
+test-ocaml *failed* | File "tests/testAvlModel.ml", line 79, characters 31-50:
+test-ocaml *failed* | 79 | type model = liquidation_slice Core_kernel.Deque.t
 
```

`Core` should replace `Core_kernel` to fix.

**Comment by purcell** [comment]
Hmm, this is odd: presumably the `earthly` build is picking up newer versions of something now, ie. it's not reproducible, since the last CI build (3 months ago) was successful. Curious why that would be, since I believe we generally tried to pin the versions of things via the Earthfile.
