### ISSUE TITLE
Model checking for AVL

### ISSUE THREAD

**Issue by murbard** [tezos-checker/checker#6]
One thing about AVL is that they land themselves decently to model checking. If you insert between 0 and 10 items in every possible order, that's only about 4 million cases to iterate through and likely goes through all the code paths. Not quite model checking, but getting close. Ditto for testing splits and deletions. Don't hesitate to write tests that take a very long time to complete for the AVL because it's by far the trickiest piece of code in this whole project and there's no harm in being somewhat exhaustive.

**Comment by gkaracha** [comment]
[`test_all_permutations`](https://github.com/tezos-checker/checker/blob/f0f5ed5c2d40a09d0da87ac83eb0565402ba0735/tests/testAvl.ml#L357-L368) already tries out 362_880 permutations (all permutations of [0..8]) which offers quite some coverage. We also have actual model checking (in [`tests/testAvlModel.ml`](https://github.com/tezos-checker/checker/blob/f0f5ed5c2d40a09d0da87ac83eb0565402ba0735/tests/testAvlModel.ml#L1-L262)), so I think we can safely close this one.
